// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416150530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$Jmo2o9x8TeD9XS0zZS4DTuDpf/UtA4fbbozFBYqpfMnU1EMqCNscq",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "$2a$11$pKYZLvGpjJ5WVof.C5PR/O7.10jY1it70T4cMBeTJ2z8nUBjQMp06",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.menon@XYZ.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Menon",
                            Phone = "9876543210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "rahul.sharma@XYZ.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Sharma",
                            Phone = "9823456781",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "anjali.verma@XYZ.com",
                            FirstName = "Anjali",
                            JoinDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Verma",
                            Phone = "9712345678",
                            Salary = 480000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "suresh.iyer@XYZ.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Iyer",
                            Phone = "9654321098",
                            Salary = 820000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2017, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "neha.gupta@XYZ.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2017, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Gupta",
                            Phone = "9543210987",
                            Salary = 900000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2017, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2016, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "Senior Software Engineer",
                            Email = "arjun.patel@XYZ.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2016, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Patel",
                            Phone = "9432109876",
                            Salary = 1200000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2016, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "divya.nair@XYZ.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9321098765",
                            Salary = 620000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "kiran.reddy@XYZ.com",
                            FirstName = "Kiran",
                            JoinDate = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9210987654",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2015, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Accounts Executive",
                            Email = "vikram.singh@XYZ.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9109876543",
                            Salary = 510000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "sneha.joshi@XYZ.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Joshi",
                            Phone = "9098765432",
                            Salary = 470000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "rohit.kumar@XYZ.com",
                            FirstName = "Rohit",
                            JoinDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kumar",
                            Phone = "8987654321",
                            Salary = 680000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "meera.pillai@XYZ.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pillai",
                            Phone = "8876543210",
                            Salary = 950000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Designation = "Senior Financial Analyst",
                            Email = "aditya.chopra@XYZ.com",
                            FirstName = "Aditya",
                            JoinDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chopra",
                            Phone = "8765432109",
                            Salary = 1100000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "pooja.desai@XYZ.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Desai",
                            Phone = "8654321098",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Designation = "Talent Acquisition Specialist",
                            Email = "manish.tiwari@XYZ.com",
                            FirstName = "Manish",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tiwari",
                            Phone = "8543210987",
                            Salary = 530000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
